trainer:
  framework: torch
  num_workers: 5
  gamma: 0.99
  num_gpus: 0.0
  kl_coeff: 1.0
  clip_param: 0.2
  model:
    fcnet_hiddens: [300, 300]
  num_envs_per_worker: 1
  train_batch_size: 20000
  sgd_minibatch_size: 2048
  batch_mode: truncate_episodes
  lr: .0003