
run_name: 'map_wide'

perf_num: 6


map_path: './f1tenth_gym/examples/hard'
map_ext: '.png'


sx: 0.0
sy: 0.0
stheta: 1.37079632679


wpt_path: './f1tenth_gym/examples/example_waypoints.csv'
wpt_delim: ';'
wpt_rowskip: 3
wpt_xind: 1
wpt_yind: 2
wpt_thind: 3
wpt_vind: 5



mass_min: 3.0
mass_max: 4.0
lf_min: 0.147
lf_max: 0.170

tlad_min: 0.2
tlad_max: 5.
vgain_min: 0.5
vgain_max: 1.5


popsize: 100
budget: 1000


optim_method: 'CMA'


seed: 12345